# Generated by Django 3.1 on 2021-04-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questio_text',
            new_name='question_text',
        ),
    ]
